services:
  lending-agent-no-wallet:
    build:
      context: ./
      dockerfile: examples/lending-agent-no-wallet/Dockerfile
    env_file:
      - examples/lending-agent-no-wallet/.env
    ports:
      - '${PORT:-3001}:${PORT:-3001}'
    restart: unless-stopped
  web:
    build:
      context: clients/web/
    container_name: chatbot
    env_file:
      - clients/web/.env
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres:17
    user: postgres
    environment:
      POSTGRES_USER: chatbot
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatbot
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: