services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatbot
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres:17
    user: postgres
    environment:
      POSTGRES_USER: chatbot
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatbot
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
