services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vibekit-web-app
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: vibekit-db
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
