services:
  swapping-agent:
    build:
      context: ../../ # Set context to the workspace root (typescript/)
      dockerfile: examples/swapping-agent/Dockerfile # Specify Dockerfile location relative to context
    container_name: swapping-agent # Optional: Give the container a specific name
    ports:
      - '${PORT:-3001}:${PORT:-3001}' # Map host port and container port using PORT env var (default 3001)
    env_file:
      - .env
    restart: unless-stopped # Optional: Policy for restarting the container

