version: '3.8'
services:
  lending-agent-no-wallet:
    build:
      context: ../../
      dockerfile: typescript/examples/lending-agent-no-wallet/Dockerfile
    env_file:
      - .env
    environment:
      - PORT=3001
    ports:
      - "3001:3001"
    restart: unless-stopped
    volumes:
      - ./:/app/typescript/examples/lending-agent-no-wallet
      - ./node_modules:/app/typescript/examples/lending-agent-no-wallet/node_modules 