services:
  lending-agent-no-wallet:
    build:
      context: ../../
      dockerfile: examples/lending-agent-no-wallet/Dockerfile
    env_file:
      - .env
    ports:
      - '${PORT:-3001}:${PORT:-3001}'
    restart: unless-stopped
